### ISSUE TITLE
running assembleDebug crashes on linux

### ISSUE THREAD

**Issue by michelemazzei** [BaseflowIT/flutter-permission-handler#105]
## 🐛 Bug Report

When run flutter run in the assembleDebug on linux get an error

here after the log:

flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              2,8s
Resolving dependencies...                                           7,0s
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
**Execution failed for task ':app:processDebugResources'.**                 
> Android resource linking failed                                       
  Output:  /home/../build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:86: error: resource android:attr/fontVariationSettings not found.
  /home/../build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:87: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /home/michele/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/2da2d4ba53882e9ff3c9aa62fbcfd11d/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/michele/Android/Sdk/platforms/android-27/android.jar\   
          --manifest\                                                   
          /home/..../build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /home/.../build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\                                                           
          @/home/.../build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /home/.../build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\                                             
          com.example.balanceapp\                                       
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /home/.../build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0                    
  Output:  /home/michele/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/de5189c4d2c58338c0f057db7575797e/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
  /home/michele/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/de5189c4d2c58338c0f057db7575797e/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
  error: failed linking references.                                     
  Command: /home/michele/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/2da2d4ba53882e9ff3c9aa62fbcfd11d/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/michele/Android/Sdk/platforms/android-27/android.jar\   
          --manifest\                                                   
          /home/.../build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /home/.../build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\                                                           
          @/home/.../build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /home/.../build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\                                             
          com.example.balanceapp\                                       
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /home/.../build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0                    
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 14s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        15,3s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

### Expected behavior
The app is not deployed on target environment

### Reproduction steps
make: flutter clean / flutter run

### Configuration

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Linux, locale it_IT.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

• No issues found!

**Platform:** 
- [x] : linux android emulator
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@michelemazzei did you update your App to support AndroidX? The compile error actually mentions the following:

>The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.

More information can also be found here: https://github.com/BaseflowIT/flutter-permission-handler/issues/98#issuecomment-484775141
