### ISSUE TITLE
Android 9: requesting phone permission will also request call log

### ISSUE THREAD

**Issue by ened** [BaseflowIT/flutter-permission-handler#115]
The Android side of the plugin currently requests access to the **phone** AND  **call log**  permissions when calling `requestPermissions` with `PermissionGroup.phone`

This is reproducible on a Android 9 phone (Pixel 2).
I propose to split this into 2 permissions (`PermissionGroup.phone`, `PermissionGroup.callLog`). 

![Screenshot_20190518-185954](https://user-images.githubusercontent.com/269860/57968591-8bc2ca00-7964-11e9-923c-b4865c120f63.png)
![Screenshot_20190518-185959](https://user-images.githubusercontent.com/269860/57968592-8e252400-7964-11e9-9b4f-028ccd462b6e.png)

**Comment by ened** [comment]
Oh, I see it's based on permissions listed in the `AndroidManifest.xml` and thus can be filtered there. Invalid issue.

**Comment by chinloyal** [comment]
@ened In my case I want to scheck the status of the call logs to see if it has been granted, but it doesn't exist on the `Permission` class as `Permission.callLogs`

**Comment by ened** [comment]
Ok , we should probably check if that permission itself exists on Android and add it as necessary.
