### ISSUE TITLE
Problem verfic permission

### ISSUE THREAD

**Issue by AlbertoTorre** [BaseflowIT/flutter-permission-handler#120]
## 💬 Questions and Help

E/flutter ( 5920): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

**Comment by mvanbeusekom** [comment]
@AlbertoTorre can you provide more information regarding this issue? Questions I have are:

- Does this affect iOS, Android or both platforms?
- Which version of the plugin are you using?
- Can you supply an example we can use to reproduce this issue (or at least a code-snippet of the code you are using now)?
- Can you include the output of `flutter doctor -v` command?
