### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by duzenko** [BaseflowIT/flutter-permission-handler#121]
I just added this plugin to project and it does not build
Am I doing anything wrong?

```
Launching lib\main.dart on LGM G600L in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

```

**Comment by izacximenes** [comment]
run `flutter clean` its work for me

**Comment by jovanovski** [comment]
I have the same issue and `flutter clean` doesn't work for me

**Comment by duzenko** [comment]
Sorry, is this plugin compatible with android x at all?
https://github.com/flutter/flutter/issues/28038#issuecomment-464466628

**Comment by ArthurKnight** [comment]
i use these two packages have the same problem!!!
how to solve?said...

image_picker: ^0.6.0+9
permission_handler: ^2.1.3

**Comment by ArthurKnight** [comment]
I use these two packages have the same problem!!!
how to solve? 

image_picker: ^0.6.0+9
permission_handler: ^3.1.0

**Comment by Allan-Nava** [comment]
Is possible to use this package to get permission for writing and reading a file in android?

**Comment by mvanbeusekom** [comment]
@duzenko please make sure you upgrade your project to support AndroidX as mentioned in the error message (and yes this plugin is compatible with AndroidX):

```
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
```

The TL;DR version is:

1. Add the following to your "gradle.properties" file:

```
android.useAndroidX=true
android.enableJetifier=true
```
2. Make sure you set the `compileSdkVersion` in your "android/app/build.gradle" file to 28:

```
android {
  compileSdkVersion 28

  ...
}
```
3. Make sure you replace all the `android.` dependencies to their AndroidX counterparts (a full list can be found here: https://developer.android.com/jetpack/androidx/migrate).

**Comment by unclexiao** [comment]
Look at this [issue](https://github.com/flutter/flutter/issues/27254)，you should update your gradle.

> I solved it by upgrading my gradle dependency in the android/build.gradle file: classpath 'com.android.tools.build:gradle:3.3.1' (I was previously on version 3.2.1)

The Code: 
```gradle
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
    }
}

```

**Comment by sedhha** [comment]
Hey guys! I have been struggling with the same problem for a long time.
Check [this](https://github.com/flutter/flutter/issues/41786#issuecomment-562820806) out it will definitely solve your issue.

**Please read all the steps properly.**
