### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by tg-admin** [BaseflowIT/flutter-permission-handler#122]
I just added this plugin to project and it does not build
Am I doing anything wrong?

![image](https://user-images.githubusercontent.com/35056021/59177540-01e6d500-8b8f-11e9-97c0-7929335ca5ae.png)

**Comment by mvanbeusekom** [comment]
@tg-admin please make sure you update your Gradle version to at least 3.4.0. Instructions can be found [here](https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1).
