### ISSUE TITLE
Build error in project after adding the package

### ISSUE THREAD

**Issue by ramamurthyk** [BaseflowIT/flutter-permission-handler#129]
## 🐛 Bug Report

After adding the package, I'm not able to build the Flutter project. Following is the error. Detailed file path/names are removed.

Launching lib\main.dart on ONEPLUS A3003 in debug mode...
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

### Expected behavior
Should build successfully.

### Reproduction steps
Create a new Flutter project in VS code, add the permission handler package and build.

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ Yes] :robot: Android

**Comment by darrenmothersele** [comment]
Slightly different error here:

```
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution
```

Building in Android Studio, on MacOS, targetting Android (One Plus device).

**Comment by darrenmothersele** [comment]
I fixed my issue by doing two things:

- a) rolling back `permission_handler` to `^3.0.0` instead of `^3.1.0`
- b) adding the suggested function by @Hixie here: https://github.com/flutter/flutter/issues/27254#issuecomment-461692152 to `build.gradle`

**Comment by mvanbeusekom** [comment]
@ramamurthyk, @darrenmothersele, this issue is caused because your project is most likely not compatible with AndroidX (as mentioned in the error message).

Please upgrade you Android project to support AndroidX using the guidelines mentioned in the error message: https://goo.gl/CP92wY

A TL;DR; version:

1. Add the following to your "gradle.properties" file:

```
android.useAndroidX=true
android.enableJetifier=true
```
2. Make sure you set the `compileSdkVersion` in your "android/app/build.gradle" file to 28:

```
android {
  compileSdkVersion 28

  ...
}
```
3. Make sure you replace all the `android.` dependencies to their AndroidX counterparts (a full list can be found here: https://developer.android.com/jetpack/androidx/migrate).

**Comment by ramamurthyk** [comment]
@mvanbeusekom @darrenmothersele - thanks a lot. Indeed it was AndroidX upgrade issue. 
I've now upgraded the project to AndroidX and can confirm that I can use this package successfully.

For info - couldn't upgrade via Android studio 'Migrate to AndroidX' option so I had to take the manual upgrade path.
