### ISSUE TITLE
Add tests and Notification permissions feature

### ISSUE THREAD

**Issue by erickjtorres** [BaseflowIT/flutter-permission-handler#131]
## 🏗 Enhancement Proposal

Was wondering if my team and I can add tests and notification permissions as a feature

### Pitch

Will allow the community to check if permissions for notifications have been allowed an or request for permissions. The tests will allow the community to have more trust on the plugin.
### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@erickjtorres, yes feel free to contribute and expand. Notification permissions would be more than welcome and having tests would definitely improve the quality of the product. 

This [article](https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/CONTRIBUTING.md) describes how to get started and feel free to ask questions.
