### ISSUE TITLE
Modal Alert Language

### ISSUE THREAD

**Issue by mamup11** [BaseflowIT/flutter-permission-handler#137]
## 💬 Questions and Help

Hi guys, I'm currently using `permission_handler: 2.1.2`and the guys from the app store reject my app because the base language is spanish, and the alert asking for the location permission shows up in English.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/10200799/62508289-b2a6d480-b7cc-11e9-8bb9-f0039c49cbbe.png">

Any idea how to change the language of the modal alert? I couldn't find anything on the readme.

**Comment by mvanbeusekom** [comment]
Yes this works using the regular Infoplist.strings files (like it would work with a normal iOS app).

A detailed explanation can be found here: https://medium.com/@guerrix/info-plist-localization-ad5daaea732a
