### ISSUE TITLE
PermissionHandlerPlugin.h file not found when archiving for iOS

### ISSUE THREAD

**Issue by scharbau** [BaseflowIT/flutter-permission-handler#142]
## 💬 Questions and Help

I'm trying to release an app to the iOS AppStore depending on permission_handler ^3.2.0
When I compile and run the project locally (on simulator and on device), it runs without problems, but when I try to archive the project for release, I always get the error message 'PermissionHandlerPlugin.h file not found'.

I tried downgrading the dependency to ^3.0.0 and ^2.2.0, but without any change in the behaviour.
Since I'm usually developing Android Apps and only recently started using flutter for developing multi platform apps, I do not know how to fix that issue myself, so any help would be welcome.

Best regards
Benjamin

**Comment by mvanbeusekom** [comment]
@scharbau did you create your app using the `-i swift` parameter (using Swift for your applications iOS native code)? 

If so you should add some additional information to your `Podfile`, see [here](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492) for more info. Make sure you use the correct version number for Swift though, version 3.2 is outdated and I think currently you should be either 5 or 4.2.

**Comment by scharbau** [comment]
@mvanbeusekom 
I generated the project using AndroidStudio, and I'm quite sure I left the checkmarks for Swift activated, I think it invokes the `-i swift` parameter.

I tried the instructions in your link, `use_frameworks!` was already present in my `Podfile`, but adding the 

> config.build_settings['SWIFT_VERSION'] = '3.2'

line while setting the version to `5.0` or `4.2` didn't change anything of the resulting behaviour.

**Comment by scharbau** [comment]
I'm actually not 100% sure if this is an issue with the plugin, with flutter, or probably only with my xCode setup.

When I use `flutter run`, `flutter build ios` or `flutter build ios --release`, the app compiles and runs without problems, on simulator and on device. Only when I open xCode and use `Project -> Archive` to upload the app to the AppStore I get the aforementioned errors.

**Comment by mvanbeusekom** [comment]
@scharbau it indeed looks like this is an issue on your end. For now I will be closing this issue, if you have more info or questions related to this issue feel free to re-open it.
