### ISSUE TITLE
Tell Users To Add Permissions IN All 3 Versions Of "AndroidManifest.xml" Files

### ISSUE THREAD

**Issue by b-cancel** [BaseflowIT/flutter-permission-handler#148]
## 🏗 Enhancement Proposal

Only Android, I have no idea of the changes needed to also reflect this for IOS

In order to ask for permission and for things to work properly its important to add the lines **similar** to the one below to EACH of the "AndroidManifest.xml" files
```
<uses-permission android:name="android.permission.INTERNET"/>
```
otherwise, you might think things are not working when you are testing your app in "profile" or "release" mode (assuming you only placed those lines in the "debug" folder)

### Pitch

Tell users to add the lines in all of these locations
1. android > app > src > **debug** > "AndroidManifest.xml" [for debug mode]
2. android > app > src > **main** > "AndroidManifest.xml" [for release mode]
3. android > app > src > **profile** > "AndroidManifest.xml" [for profile mode]

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by b-cancel** [comment]
@martijn00 let me know if something isn't clear so we can work to help other devs!

**Comment by cremor** [comment]
Are you sure that it isn't enough if you place it just in the "main" file? I've tested this and it works also for debug builds.

**Comment by b-cancel** [comment]
@cremor to be frank I haven't tested if it breaks anything with this particular plugin... but with the 2nd most popular permission plugin... if you don't do this things break

I imagine this implementation is the same with slight tweaks which is why I suggested it

If you want to confirm if it's an issue or not see if profile and release mode both work if the lines are only in the debug androidmanifest.xml file

Or I could do this and let you know

**Comment by cremor** [comment]
Why would I only add a permission to the file in the "debug" folder? All documentation that I ever read about Android permissions for Flutter said to add it to the file in the "main" folder.

**Comment by b-cancel** [comment]
@cremor that's what I meant 
I apologize 
I just wanted to answer before I snoozed but shouldn't have cuz I'm half asleep

**Comment by b-cancel** [comment]
@cremor you are current
after further testing and inspection, they only need to be in the one in 
android > app > src > main > "AndroidManifest.xml" [for release mode]

Either way!

This is nowhere in the docs and it should be

**Comment by mvanbeusekom** [comment]
@b-cancel I have just updated the docs with more information and links to example `AndroidManifest.xml` and `Info.plist`. 

Thanks for informing us about this issue, I really appreciate it.
