### ISSUE TITLE
Runtime permissions is not working as Expected on iOS

### ISSUE THREAD

**Issue by hemandroid** [BaseflowIT/flutter-permission-handler#150]
Hi Team,

I tried your sample app which the Runtime permissions plugin of your's. It is working fine in Android using emulator and real-device aswell. But in iOS app is getting crash and connection is getting lost in Android Studio. Please check this issue, by the it doesn't print any log response for iOS issue.

**Comment by mvanbeusekom** [comment]
@hemandroid I cannot reproduce this issue. I am able to run the example app using Visual Studio Code, IntelliJ and the Flutter CLI (I experience no crashes and request permissions just fine on an iPhone 7 and several simulated iPhone models). 

Seems to me this is a local issue on your end.

**Comment by hemandroid** [comment]
Thank you @mvanbeusekom for your response. As you said, issue was happened due to some local cache. Now the code is working fine as expected. Thanks for your efforts for providing such a useful plugin.
