### ISSUE TITLE
Is it possible to request specific permissions rather than the permission group?

### ISSUE THREAD

**Issue by jagan999** [BaseflowIT/flutter-permission-handler#163]
## 🚀 Feature Requests

Provide another method that allows us to request a specific permission rather than the entire group

### Contextualize the feature
Use case for this feature request. My app only needs to read SMS but does not need to send SMS. When I submitted my app asking for the SMS group permission, it was rejected by Google saying my app doesn't need Send SMS permission but it is asking user to grant that permission without any need.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X ] :robot: Android

**Comment by mvanbeusekom** [comment]
@jagan999 yes this is possible (although not entirely straight forward). 

Currently the plugin checks which permissions you have listed in your AndroidManifest.xml and only request those permissions. In your case, if you only have to add the `<uses-permission android:name="android.permission.READ_SMS"/>` permissions to your AndroidManifest.xml.

Now when you call the `requestPermissions` with the `PermissionGroup.sms` permission group, your App should only request permissions to read sms messages.
