### ISSUE TITLE
PermissionHandlerPlugin.java: uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by menezes85** [BaseflowIT/flutter-permission-handler#167]
## 🏗 Enhancement Proposal

Hello, please review code of your package, AS claims about deprecated code.
permission_handler-3.3

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [x ] :robot: Android

**Comment by mvanbeusekom** [comment]
@menezes85 can you be a bit more elaborate? Maybe you can supply us with some log output? 

Do you know that it is specific to our plugin? I know that Flutter itself also makes calls to some deprecated methods which happen to show up in the logs.

**Comment by menezes85** [comment]
hello @mvanbeusekom , 
here follows the part that AS reports deprecation:

PermisionHandlerPlugin.java , Line 182, 616 and 617.

` case Manifest.permission.PROCESS_OUTGOING_CALLS:`

public static final String PROCESS_OUTGOING_CALLS
According to documentation:

This constant was deprecated in API level 29.
Applications should use CallRedirectionService instead of the Intent.ACTION_NEW_OUTGOING_CALL broadcast.

**Comment by menezes85** [comment]
when this will be out ??

**Comment by peterpahaaan** [comment]
In my case I got the following error. My project doesn't build, if I add the package.

Note: C:\Users\UserX\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-3.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionHandlerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Finished with error: Gradle task assembleDebug failed with exit code 1



-----------------------------
compileSdkVersion 28
minSdkVersion 23
targetSdkVersion 28
