### ISSUE TITLE
Building on iOS fails

### ISSUE THREAD

**Issue by PauloMelo** [BaseflowIT/flutter-permission-handler#17]
This is the return from Xcode.
Header 'permission_handler-Swift.h' not found

**Comment by mvanbeusekom** [comment]
@paulomelo this it not really a bug in the plug-in, bit more a shortcoming in the way Flutter handles Swift. The Flutter team is hard at work on solving this issue. 

In the meantime you can implement a simple workaround by adding a few lines of code to you iOS podfile. More information can be found here: [Flutter#16049](https://github.com/flutter/flutter/issues/16049)

**Comment by mvanbeusekom** [comment]
@paulomelo this it not really a bug in the plug-in, bit more a shortcoming in the way Flutter handles Swift. The Flutter team is hard at work on solving this issue. 

In the meantime you can implement a simple workaround by adding a few lines of code to you iOS podfile. More information can be found here: [Flutter#16049](https://github.com/flutter/flutter/issues/16049)
