### ISSUE TITLE
1.0.1 & 2.0.0 version

### ISSUE THREAD

**Issue by penjual** [BaseflowIT/flutter-permission-handler#22]
## 🐛 Bug Report

=== BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/xxx/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.0.0/ios/Classes/PermissionHandlerPlugin.m:2:9: fatal error: 'permission_handler/permission_handler-Swift.h' file not found
#import <permission_handler/permission_handler-Swift.h>

### Configuration
Cocoapods 1.5.3

Podfile
...
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      **config.build_settings['SWIFT_VERSION'] = '4.1'**
    end
  end
end
...

**Version:** 1.0.1 & 2.0.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by penjual** [comment]
Solved:
- Build new project with 👍 -i swift

**Comment by Nk54** [comment]
Hello @penjual I face the same problem, where did you put -i swift please ?

**Comment by Nk54** [comment]
Nevermind, adding use_frameworks!  made it. See below : 
target 'Runner' do
  use_frameworks! # flutter_swift_compile
