### ISSUE TITLE
Undefined class 'PermissionStatus'.

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [BaseflowIT/flutter-permission-handler#27]
## 🐛 Bug Report

Cannot compile and run from main (Is this even supposed to be run?)
Dart Analysis error: _Undefined class 'PermissionStatus'. (undefined_class at [permission_handler] lib/utils/codec.dart:5)_
### Expected behavior
No errror
### Configuration

**Version:** 2.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @ThinkDigitalRepair, I am affraid that it is not clear to me what you are trying to do. 

This project is a plugin and as such is not supposed to run. Its purpose is to enable other developers to use it in their App so they don't have to implement permission mechanics themselves. The project does however comes with a simple example App which demonstrate the usage of the plugin (see the code in the "[example](https://github.com/BaseflowIT/flutter-permission-handler/tree/develop/example)" folder). This App can be run using the following commands:

```shell
# Make sure you change to into the "example" directory
cd example
# Run the "example" app
flutter run
```

Just to be sure I have tested the above and the code compiles and the example app runs on both iOS and Android.
