### ISSUE TITLE
Kotlin version doesn't compile

### ISSUE THREAD

**Issue by jaumard** [BaseflowIT/flutter-permission-handler#33]
## 🐛 Bug Report

```
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'permission_handler' is using version 1.2.30.
```

Same problem for geolocator and google_api_availability... :(

### Reproduction steps
Basic usage with last Android Studio and gradle 3.2.0

**Version:** last

**Platform:** 
- [ ] :iphone: iOS
- [*] :robot: Android

**Comment by jaumard** [comment]
I'm using geolocator only but as it's this plugin that crash first I put the issue on this one :) I'll wait for the geolocator update then ;) 
Thanks !

**Comment by mvanbeusekom** [comment]
@jaumard, we just released version 2.1.0 of the Geolocator plugin, this should solve the issues you were experiencing

**Comment by jaumard** [comment]
Thanks, now I'm having: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

```
No more error once geolocator is removed

**Comment by mvanbeusekom** [comment]
@jaumard this is caused by different plugin depending on different versions of the `com.google.android.gms:play-services`. One way to solve it is to install this gradle plugin (requires a little bit of editing of your `build.gradle` file:

https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-

**Comment by mvanbeusekom** [comment]
@jaumard if you are not using any other plugins (or you know that they all use version 16.0.1 of the `com.google.android.gms:play-services`) you could try removing your `~/.gradle` folder. This will remove all cached versions of the libraries and download them again. Sometimes this helps.

Other useful link is:
- https://github.com/flutter/flutter/issues/22614

**Comment by g123k** [comment]
The solution is to upgrade your Gradle wrapper version.

Open this file: `android/gradle/wrapper/gradle-wrapper.properties`

And update the following line:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
