### ISSUE TITLE
A problem occurred configuring project ':permission_handler'.

### ISSUE THREAD

**Issue by timtraversy** [BaseflowIT/flutter-permission-handler#35]
## 🐛 Bug Report

I'm using the permission_handler library in my Flutter project. It builds fine on iOS, but throws an error when I try to build on Android. It configures all my other plugins correctly, but it fails on this one for some reason.
<img width="898" alt="screen shot 2018-10-18 at 2 29 27 pm" src="https://user-images.githubusercontent.com/21370530/47175872-39dc9780-d2e2-11e8-955a-14d1a0a87156.png">

Maybe this is conflicting with a Kotlin or Gradle version? My Kotlin version is `1.2.51`, Gradle is `3.2.1`, targetSdkVersion is `27`.

As recommended by this [flutter issue comment](https://github.com/flutter/flutter/issues/14020#issuecomment-380178542),  I also have this included in my project level `build.gradle` file:

```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }
        }
    }
}
```

### Expected behavior

Plugin builds successfully.

### Reproduction steps

Build Flutter project on Android with most recent permission_handler library as dependency.

### Configuration

**Version:** 2.1.0

**Platform:** 

- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by timtraversy** [comment]
I just created a new flutter project and included the same dependency, and the issue happened again, so it's not just an issue in my current project.

**Comment by mvanbeusekom** [comment]
@timtraversy could you post the contents of your `build.gradle` and `gradle-wrapper.properties` files?

**Comment by timtraversy** [comment]
Upgrading my Kotlin version to 1.2.71 fixed the error with your library, although it's now breaking an unrelated part of the flutter build process. But all is well here I believe!
