### ISSUE TITLE
execution stops on requesting permission

### ISSUE THREAD

**Issue by totalerex** [BaseflowIT/flutter-permission-handler#36]
## 🐛 Bug Report

`
 Map<PermissionGroup, PermissionStatus> permissions =
    await PermissionHandler().requestPermissions([PermissionGroup.calendar]);
`

Device shows permission request, whatever user selects accept or decline the execution stops at that string. It doesn't stop if permission already granted.

Calendar permission defined in manifest.

plugin version v.2.1.0
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.2)
[√] Connected devices (1 available)

On performing Hot Reload - Console shows: 

E/flutter ( 2113): PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null)

**Comment by mvanbeusekom** [comment]
@totalerex I am having a hard time reproducing this error. Would you be able to supply a small example that reproduces this error? This will help hugely in debugging this issue.

**Comment by mvanbeusekom** [comment]
Closing the issue since lack of activity. Feel free to re-open this issue when it is still relevant (but please provide the requested additional information)
