### ISSUE TITLE
hi,i meet a problem when building a ios project

### ISSUE THREAD

**Issue by hyz1992** [BaseflowIT/flutter-permission-handler#37]
this is xcode message box tip:
The target “permission_handler” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

there is also other plugin writed by swift,such as fluwx. but only permission_handler show that error.
hao should i do?
thanks!

**Comment by mvanbeusekom** [comment]
@hyz1992, which version of the `permission_handler` are you using? Our latest versions (at least version 2 and higher) are compiled using Swift 4 and Xcode 10.

**Comment by hyz1992** [comment]
thanks,the version is lastest,but my Xcode is 9.4.1,I'm upgrading it and will try again

**Comment by hyz1992** [comment]
Hi,I have upgrade my Xcode to 10.1,but the problem still exist.
frist,I run my helloworld project In VsCode: the log is:
`
=== BUILD TARGET permission_handler OF PROJECT Pods WITH CONFIGURATION Debug ===
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
Could not build the precompiled application for the device.
`

then I open this project in Xcode,still show a error message box:
`
The target “permission_handler” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets.
Use Xcode 8.x to migrate the code to Swift 3.
`

then I manually change the Swift Language Version to 4.0 in build setting.
Xcode say 'permission_handler/permission_handler-Swift.h' file not found.

sorry,I am a newer of ios,I hope that I have described it clearly.
thanks much for your help!

**Comment by mvanbeusekom** [comment]
Hi @hyz1992, no problem at all.

Now I see the problem and it can be solved quite easily. You will just have to update your `Podfile` which should be in the root of you `ios` folder. Simply add the following line to the `post_install` block:

```
config.build_settings['SWIFT_VERSION'] = '4.1'
```

The end result should look similar to this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end
```

More information can be found here [flutter/flutter#16049](https://github.com/flutter/flutter/issues/16049)

**Comment by naumanahmed19** [comment]
kindly also mention this in the description. I have wasted a  day on this.  🥇

**Comment by mvanbeusekom** [comment]
@naumanahmed19 which version of the plugin are you using? We had hopes that for the latest version (2.1.1) this is no longer necessary.

**Comment by naumanahmed19** [comment]
I am using geolocator: ^2.1.0 
https://pub.dartlang.org/packages/geolocator#-installing-tab-

**Comment by surrenderios** [comment]
try this, works for me
https://github.com/Ethras/flutter_simple_permissions/issues/51#issuecomment-434648578

**Comment by Shentia** [comment]
> Hi @hyz1992, no problem at all.
> 
> Now I see the problem and it can be solved quite easily. You will just have to update your `Podfile` which should be in the root of you `ios` folder. Simply add the following line to the `post_install` block:
> 
> ```
> config.build_settings['SWIFT_VERSION'] = '4.1'
> ```
> The end result should look similar to this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>       config.build_settings['SWIFT_VERSION'] = '4.1'
>     end
>   end
> end
> ```
> More information can be found here [flutter/flutter#16049](https://github.com/flutter/flutter/issues/16049)

It's Not work to me :(
