### ISSUE TITLE
 Could not resolve project :permission_handler.

### ISSUE THREAD

**Issue by OMP1024** [BaseflowIT/flutter-permission-handler#40]
## 🐛 Bug Report
![image](https://user-images.githubusercontent.com/10349293/48107411-787ac780-e27a-11e8-9cb6-a010cfd0b57c.png)

### Configuration

**Version:** ^2.1.0

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@OMP1024 I need more information to help you with this issue. I can't reproduce the problem you are facing with the little information you provided. Here is what I did:

- First of I cloned the current version of the `permission_handler` project and executed the `example` project. This works fine.

- Second I created a new Flutter App (using Android Studio) and added the `permission_handler` plugin and made sure I request some permissions (in my case I requested permissions to access the calendar). Also this worked fine out of the box. 

Here is my environment:
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14 18A391, locale en-NL)
    • Flutter version 0.10.2 at /Users/maurits/Developer/flutter
    • Framework revision d8cbb80206 (12 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by mvanbeusekom** [comment]
@yathit thank you for the additional information. This error is most likely caused by an outdated version of Gradle. Please update your Gradle dependencies using the following instructions:

- flutter/flutter#22614
- Or copy the changes in this [PR](https://github.com/flutter/flutter/pull/22790/files) to your own project
