### ISSUE TITLE
Request permission not wait for user action

### ISSUE THREAD

**Issue by DineshKachhot** [BaseflowIT/flutter-permission-handler#44]
### Code Snippet 
```
    PermissionStatus permission = await PermissionHandler()
        .checkPermissionStatus(PermissionGroup.location);
    if (permission == PermissionStatus.unknown ||
        permission == PermissionStatus.denied) {
      Map<PermissionGroup, PermissionStatus> permissions =
          await PermissionHandler()
              .requestPermissions([PermissionGroup.location]);

      if (permissions[PermissionGroup.location] == PermissionStatus.granted) {
        platform.invokeMethod('locationPermissionGranted');
      }
    }

```
### Expected behavior

While I am using `async await` to wait for user to take action, it should call next line only after user user take any action, but next line is never execute, I tried print and break point.
 
### Reproduction steps

Try put the code in blank flutter app and call a function after permission received.

### Configuration

**Version:** 
Flutter version:- 

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (7 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by hoangcao10** [comment]
same issue

**Comment by ozeksi** [comment]
I am able to solve it by removing `checkPermissionStatus` part. Now I am directly calling `requestPermissions ` and it immediately returns if the permission is already granted or denied before.
