### ISSUE TITLE
False negative returned from by openAppSettings method on iOS

### ISSUE THREAD

**Issue by mvanbeusekom** [BaseflowIT/flutter-permission-handler#52]
## 🐛 Bug Report

Calling the `bool isOpened = await PermissionHandler().openAppSettings();` method on iOS opens the settings page but returns `false`. 

### Expected behavior

When the setting page is opened the expected result for this method should be `true`.

### Reproduction steps

Start the example App on iOS and hit the "Open Settings Page" icon (right top of the screen). Catch the boolean to see it returns false.

### Configuration

**Version:** 2.1.2

**Platform:** 
- [x] :iphone: iOS

**Comment by dark-chocolate** [comment]
I tested it in iOS 12.0.1 running in iPhone 6s.
