### ISSUE TITLE
I'm having the same issue. I'm trying to use 2.1.2 and I'm using 10.1. I've done a clean and upgrade on packages. Any thoughts?

### ISSUE THREAD

**Issue by smokinguns** [BaseflowIT/flutter-permission-handler#53]
_Originally posted by @smokinguns in https://github.com/BaseflowIT/flutter-permission-handler/issues/49#issuecomment-443422109_

**Comment by mvanbeusekom** [comment]
@smokinguns , I have just made some tests with a brand new project. I had to make the two changes documented here Flutter#16049 to my `Podfile` (listed in the `ios` folder). After doing so my project compiled correctly.

For you convenience here are the changes:

1. In your `Podfile` make sure you add the line `use_frameworks!` (best is to add this line directly below the `target Runner do` like so:

```
target 'Runner' do
  use_frameworks!
```

2. Also in your `Podfile` make sure you add the line `config.build_settings['SWIFT_VERSION'] = '4.2'` to the `post_installer` block. After adding this line the `post_installer` block should look like this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```

Our hope was that this would no longer be necessary, however unfortunately it still is :(. Please let us know if you experience any further issues.

**Comment by smokinguns** [comment]
appreciate it, unfortunately this was my first attempt at flutter.  
this line did fix it -> config.build_settings['SWIFT_VERSION'] = '4.2' 
Thanks for your help

**Comment by mvanbeusekom** [comment]
@smokinguns, great to hear this helped. Thank you for the feedback (and not to worry, we are all relatively new with Flutter) ;).
