### ISSUE TITLE
Building for iOS fails plugin version 2.1.2

### ISSUE THREAD

**Issue by Gavmcdonald** [BaseflowIT/flutter-permission-handler#57]
## 🐛 Bug Report

Building for iOS fails
>    === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:50:45: error: type 'UIApplication' has no member 'UIApplicationOpenSettingsURLString'
                    guard let url = URL(string: UIApplication.UIApplicationOpenSettingsURLString),
                                                ^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/ios/Classes/PermissionManager.swift:59:77: error: type 'UIApplication' has no member 'UIApplicationOpenSettingsURLString'
                    let success = UIApplication.shared.openURL(URL.init(string: UIApplication.UIApplicationOpenSettingsURLString)!)

**Version:** 2.1.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by kmckinley** [comment]
Running into the same problem.

**Comment by chenparty** [comment]
the same problem, only in ios .

**Comment by deepak-gehlot** [comment]
Same problem, only in IOS.

**Comment by daryll-fourie** [comment]
Same problem on my side, also only in iOS... Any update on this?

**Comment by daryll-fourie** [comment]
Forcing Flutter to use V2.1.0 fixes the problem for now...
(And if you use the "Geolocator" package, then force both packages to use V2.1.0)
 
#example code
`geolocator: 2.1.0`
`permission_handler: 2.1.0`

Remember to run `flutter clean` in the terminal and then `get` your .yaml dependencies again before running your app.

**Comment by firsthour** [comment]
I had to downgrade geolocator to 2.0.2 and permission_handler to 2.0.1 to get this to work.

**Comment by b4rtaz** [comment]
Version 2.1.2 works after I've updated `ios/Podfile`:

```
target 'Runner' do
  use_frameworks! # < add this!
```

**Comment by gburnham** [comment]
Thank you @daryll-fourie! I should have looked here first!

**Comment by ahmedb** [comment]
I had this problem too. The root-cause is actually that the project generated by Flutter is actually set a "Swift 4.0" instead of "Swift 4.2".

I had a Pull Request but closed it because I wasn't sure if it was appropriate to roll back the changes for everyone. 

There are a couple of ways to fix this:
1. Manually update your "Runner.xcodeproj" to use "4.2" for "Swift Language Version" (You need to update the Project AND Target)
2. Roll back to tag 2.1.0 or pull a fork with the API rollback (I put the changes on my 'develop' fork: https://github.com/ahmedb/flutter-permission-handler)

**Comment by 562218352** [comment]
1: down grade permission_handler's version to 2.1.0
     if running into this error :  can't find file :<permission_handler/permission_handler-Swift.h>  , then go the sec step.
2： open permission_handler source code, find "PermissionHandlerPlugin.m" ,  
 and  edit <permission_handler/permission_handler-Swift.h>  into "permission_handler-Swift.h"         

solve my issue

**Comment by muhammadkhayyam** [comment]
Dear 562218352 , 
Can you explain in detail your resolution , I am new to mobile development, your detail help will be highly appreciated.

Thanks.

**Comment by dokinkon** [comment]
@daryll-fourie That worked for me.

**Comment by mvanbeusekom** [comment]
@muhammadkhayyam, @ahmedb, @562218352, to be able to use version 2.1.2 of the permission handler you'll have to use Xcode 10.1 or higher and make sure you update your Podfile to reflect the following changes:

In your Podfile make sure you add the line use_frameworks! (best is to add this line directly below the target Runner do like so:
```
target 'Runner' do
  use_frameworks!
```
Also in your Podfile make sure you add the line `config.build_settings['SWIFT_VERSION'] = '4.2'` to the post_installer block. After adding this line the post_installer block should look like this:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```
