### ISSUE TITLE
Permission dialogs are not popping up

### ISSUE THREAD

**Issue by fritz-playmaker** [BaseflowIT/flutter-permission-handler#58]
## 🐛 Bug Report

Inserted the permission boiler-plate code  but permission dialogs are not popping up 

`  Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler().requestPermissions([PermissionGroup.location]);`

I also inserted the permission in the Android Manifest
` <uses-permission android:name="android.permission.LOCATION"/>`

**Version:** 2.1.2

**Platform:** 
- [ ] :iphone: iOS
- [Y] :robot: Android

**Comment by debottam31** [comment]
In My Case Permission Handler is not working properly in iOS

> Map<PermissionGroup, PermissionStatus> locationPermisson =  await permissonhandler
>         .requestPermissions([PermissionGroup.location]);

this one taking forever to show the popup on screen

**Comment by debottam31** [comment]
@fritz-playmaker any update on this, the popup is not coming in ios for me, but in the case, for Android, it is working properly

**Comment by fritz-playmaker** [comment]
Android working now

**Comment by Wels2001** [comment]
Hola alguien me podía explicar como implementar este paquete a mi proyecto? ;)

**Comment by mvanbeusekom** [comment]
@debottam31 have you included the required lines in your `Info.plist` file? For location you should add the following lines:

```
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Need location when in use</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Always and when in use!</string>
	<key>NSLocationUsageDescription</key>
	<string>Older devices need location.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Always and when in use!</string>
```

More information about these permissions can be found [here](https://medium.com/curbside/requesting-location-permissions-in-ios-9e5a3b814a8b), read the "Usage descriptions" paragraph.

**Comment by mvanbeusekom** [comment]
Closing this issue since OP has resolved his problem.
