### ISSUE TITLE
Feature Request: Remove Kotlin dependency

### ISSUE THREAD

**Issue by vladaman** [BaseflowIT/flutter-permission-handler#61]
## 🚀 Feature Requests

We don't use Kotlin and we'd welcome Permissions module without this dependency.

**Comment by mvanbeusekom** [comment]
Hello @vladaman, we develop all our native Android code using Kotlin to make our development experience better and improve the quality of our code (in case you are interested here is a nice article which sets out all benefits of using Kotlin over Java: https://medium.com/@magnus.chatt/why-you-should-totally-switch-to-kotlin-c7bbde9e10d5).

Unless there is a very valid reason, which we have overlooked (other then "it saves a dependency"), we are not going to switch and rebuild the plugin in an outdated programming language.
