### ISSUE TITLE
Doesn't support Android X and build keeps breaking

### ISSUE THREAD

**Issue by vishvajit79** [BaseflowIT/flutter-permission-handler#68]
Migrate from the deprecated original Android Support Library to AndroidX. This shouldn't result in any functional changes, but it requires any Android apps using this plugin to also migrate if they're using the original support library.

**Comment by AnilNewari** [comment]
Now working with AndroidX.

**Comment by mvanbeusekom** [comment]
@vishvajit79 this problem is solved in version 2.1.3 of the plugin which was released on the 11th of February
