### ISSUE TITLE
Build failed because of Kotlin Gradle plugin version

### ISSUE THREAD

**Issue by Yahhi** [BaseflowIT/flutter-permission-handler#70]
## 🐛 Bug Report

When I have added the library to my project it failed to build. 
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':permission_handler' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

### Expected behavior
Build should be successful

### Reproduction steps
Add the library to project with androidX support

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [v] :robot: Android

**Comment by nemoryoliver** [comment]
Same here.

**Comment by mvanbeusekom** [comment]
Should be solved in version 2.1.3 of the plugin which was released 11th of Februari
