### ISSUE TITLE
2.1.3 is a breaking change on android

### ISSUE THREAD

**Issue by Henge9** [BaseflowIT/flutter-permission-handler#74]
## 🏗 Enhancement Proposal

When a breaking change is done please make a bigger change to the version. 
The upgrade to androidX breaks builds with the old android support library.

### Pitch

If 2.1.3 was 3.0.0 my gradle build would not have failed and alot of gradle version hell could have been avoided.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

And by the way: Thank you for a nice plugin.

**Comment by mvanbeusekom** [comment]
@Henge9, thank you very much for the feedback. You are absolutely right, I completely missed it and will keep it in mind for future updates (version 2.2.0 is coming today with a new feature).

**Comment by Henge9** [comment]
Thank you for the fast reply. Not even google managed to do it correctly as the link below shows. 

https://github.com/flutter/flutter/wiki/Postmortem:-AndroidX-plugin-migration
