### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ened** [BaseflowIT/flutter-permission-handler#83]
## 🏗 Enhancement Proposal

Please update the pub changelog.

### Pitch

There is a new major version 3.0.0, which improves compatibility and performance & it should be documented in the changelog.

Thank you.

**Comment by j3g** [comment]
I also noticed this today while beginning my integration process. The docs are misleading.

**Comment by mvanbeusekom** [comment]
Solved, thanks for pointing it out
