### ISSUE TITLE
No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods

### ISSUE THREAD

**Issue by mrcoalp** [BaseflowIT/flutter-permission-handler#87]
Every function I try to call it throws the same error! 'No implementation on channel'

"MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)"

**Version:** 3.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mrcoalp** [comment]
My bad... AndroidX... -.- It works fine! Thanks :)

**Comment by MazEbeid** [comment]
I have the same issue, could you please let me know how you fixed it?

**Comment by ueabu** [comment]
Hey, how did you fix this? I am having the same issue.

**Comment by mrcoalp** [comment]
> I have the same issue, could you please let me know how you fixed it?

Didn't see this until now, sorry. Migration to AndroidX fixed this for me

**Comment by MazEbeid** [comment]
I have decided to use this plugin which solves it for me.

https://pub.dartlang.org/packages/simple_permissions

**Comment by softmarshmallow** [comment]
Using android X, still having same issue

**Comment by Zoki92** [comment]
I've added the package and updated android manifest, was already using androidX from before and when I tried to run it got the same error. Running flutter clean solved it for me.

**Comment by ricrsantos** [comment]
Hi Folks! In my case the problem was conflict between two plugins, Facebook sign in  and Permissions. To fix I just cut off the facebook plugin.

**Comment by DenisKen** [comment]
I'm having this issue. I just tried to apply all solutions to solve it, but none worked.
The bug happens with Facebook-Sign-in Plugin, but I depend on it.

I've tried to apply **multiDexEnabled true** and change 
**minSdkVersion 16** to **minSdkVersion 21**. None worked.

**Comment by exploringpratik** [comment]
> Hi Folks! In my case the problem was conflict between two plugins, Facebook sign in and Permissions. To fix I just cut off the facebook plugin.

For me also, it is working after removing facebook and google sign in packages.

**Comment by pluzmedia** [comment]
Is this plugin would work on Flutter Web?

**Comment by Abhishek01039** [comment]
Hi @pluzmedia 
https://pub.dartlang.org/packages/simple_permissions
This plugin is not available for the web as of now

**Comment by pluzmedia** [comment]
Hi @Abhishek01039 

Is it possible to disable on web platform?

**Comment by Abhishek01039** [comment]
Hi @pluzmedia 
`kIsWeb` constant is there for check that flutter is running on the web or not 
if flutter is running on the web then it is returning true otherwise false
so you can use this constant 
if flutter on the web then don't use these two plugins 
Thanks

**Comment by pluzmedia** [comment]
Hi @Abhishek01039,

thanks, it's working

**Comment by donbay01** [comment]
> I've added the package and updated android manifest, was already using androidX from before and when I tried to run it got the same error. Running flutter clean solved it for me.

You added which package

**Comment by aniketsongara** [comment]
Having same issue 
`MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)`

But in my case it's happening only in app release mode, and after too much time I got, Issue is coming due to using 
permission_handler and file_picker packages in my pubspec.yam 
After removing any of them working fine but not working together.
please give any suggestions how can I resolve it.

I run flutter clean but still having same issue also tried to

**Comment by aniketsongara** [comment]
My issue has been solved by adding two line of code in my `android/app/build.gradle
`
```
buildTypes {
       release {
           shrinkResources false
           minifyEnabled false
           signingConfig signingConfigs.release
       }
   }
```
