### ISSUE TITLE
Always says "No permissions found in manifest"

### ISSUE THREAD

**Issue by vendramini** [BaseflowIT/flutter-permission-handler#91]
## 💬 Questions and Help

Hello,

I copied and paste the example: https://github.com/BaseflowIT/flutter-permission-handler/tree/develop/example both `main.dart` and the permissions inside `AndroidManifest.xml`.

The message is always the same:

```
Launching lib/main.dart on SM G935F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM G935F...
D/libGLESv2( 2235): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.flutter_app
D/permissions_handler( 2235): No permissions found in manifest for: $permission
I/chatty  ( 2235): uid=10519(u0_a519) com.example.flutter_app identical 5 lines
D/permissions_handler( 2235): No permissions found in manifest for: $permission
D/permissions_handler( 2235): No permissions found in manifest for: $permission
I/chatty  ( 2235): uid=10519(u0_a519) com.example.flutter_app identical 3 lines
D/permissions_handler( 2235): No permissions found in manifest for: $permission
D/ViewRootImpl@6bcba18[MainActivity]( 2235): ViewPostIme pointer 0
D/ViewRootImpl@6bcba18[MainActivity]( 2235): ViewPostIme pointer 1
D/permissions_handler( 2235): No permissions found in manifest for: $permission
I/flutter ( 2235): decodePermissionRequestResult called with: value:[{0: 4}]
I/flutter ( 2235): {PermissionGroup.calendar: PermissionStatus.unknown}
I/flutter ( 2235): PermissionStatus.unknown
```
No matter what I do. Even tried more simple code, like just asking for one permission clicking a button.

I do have all the permissions on manifest.

Any clues?

**Comment by sid19991** [comment]
I also have the same problem.

**Comment by recvec** [comment]
+1

**Comment by gmacklem** [comment]
Same here.  I believe it is due to the latest update to Flutter and Dart.  I am getting errors on other packages as well since the upgrade.

**Comment by vendramini** [comment]
Any progress? I just can't proceed my tests and I didn't find anything about this.

**Comment by gwalaniarun** [comment]
I am also facing same problem.

**Comment by vendramini** [comment]
I'm trying to debug by myself and I found something (I guess).

PermissionHandlerPlugin.java
```java
PackageInfo info = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);
mRequestedPermissions = new ArrayList<>(Arrays.asList(info.requestedPermissions));
```
The method `info.requestedPermissions` supposedly should bring to us all the `<uses-permissions/>` inside `AndroidManifest.xml`.

I did a `Log.d(LOG_TAG, mRequestedPermissions.toString());` and the result is always: `D/permissions_handler(25583): [android.permission.INTERNET]` no matter what.

So the method `hasPermissionInManifest` always return false.

Keep trying...

**Comment by vendramini** [comment]
I do have news.

When creating the apk for `debug`, it ALWAYS compile just the `android.permission.INTERNET` inside apk. I figured out listing the permissions with: `aapt d permissions /path/to/com.your.package.apk`.

When creating the apk for `release`, all the permissions are injected.

Probably the problem is the way Flutter are compiling.

![image](https://user-images.githubusercontent.com/510878/54782948-e3f87c80-4bfe-11e9-8376-ee6628636272.png)

**Comment by vendramini** [comment]
Well, I just created a new project with latest flutter SDK and everything is working.

**Comment by samosudov** [comment]
In my case the problem solved with command `flutter clean`

**Comment by cohenadair** [comment]
> In my case the problem solved with command `flutter clean`

Thank-you, @samosudov!

**Comment by lokeshpaladugula** [comment]
> In my case the problem solved with command `flutter clean`

still not working bro

**Comment by lokeshpaladugula** [comment]
https://stackoverflow.com/q/61591655/11394781


please some one help me bro

**Comment by samosudov** [comment]
> https://stackoverflow.com/q/61591655/11394781
> 
> please some one help me bro

@lokeshpaladugula answered
https://stackoverflow.com/a/61592105/5451349

**Comment by akbarraihanm** [comment]
> > https://stackoverflow.com/q/61591655/11394781
> > please some one help me bro
> 
> @lokeshpaladugula answered
> https://stackoverflow.com/a/61592105/5451349

not working on me

**Comment by GrapevineLin** [comment]
still have this problem😭

**Comment by thukyaw11** [comment]
still having the problem :33

**Comment by thukyaw11** [comment]
got it by reinstalling the app and clearing cache

**Comment by omerasif57** [comment]
Still having it. even @thukyaw11 trick didn't help.

**Comment by oreo** [comment]
In my case the problem solved with permission_handler: 5.1.0+2

**Comment by velval** [comment]
@oreo this also worked for me.

**Comment by aryant-nigam** [comment]
I am having problem despite using flutter clean and even putting relevant permissions in manifest

**Comment by naqeeb9a** [comment]
@aryant-nigam  in my case i had that file already downloaded in the path which i was trying to download again and again it it showed me error of no permission and after i deleted that file it worked

**Comment by New-dev0** [comment]
Restarting Android studio worked for me🤧
