### ISSUE TITLE
Add cocoapods' static_framework support

### ISSUE THREAD

**Issue by toby1991** [BaseflowIT/flutter-permission-handler#92]
## 🚀 Feature Requests

add cocoapods' `static_framework` support
https://github.com/CocoaPods/CocoaPods/pull/6811

### Contextualize the feature

We must add `use_frameworks!` at `Podfile`, but after add these configurations, will cause many problems such as below:

```bash
error: exportArchive: permission_handler.framework does not support provisioning profiles.

Error Domain=IDEProvisioningErrorDomain Code=10 "permission_handler.framework does not support provisioning profiles." UserInfo={NSLocalizedDescription=permission_handler.framework does not support provisioning profiles., NSLocalizedRecoverySuggestion=permission_handler.framework does not support provisioning profiles, but provisioning profile match AdHoc com.xxx.app has been manually specified. Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}
```

and that will cause the Archive success but Sign failed error.

### Describe the feature

> CocoaPods version 1.3.1 and earlier do not support static framework 
 dependencies.CocoaPods 1.4.0 adds thestatic_framework option in #6811 that enables you 
 to specify building a pod as a static_framework, which unlike dynamic frameworks, can have static framework dependencies.

add `s.static_framework = true` to `.podspec`

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS

**Comment by mvanbeusekom** [comment]
@toby1991 we just published version 3.0.1 of the Permission Handler plugin which implemented this feature. Thank you for you suggestion and clear explanation.
