### ISSUE TITLE
resource android:attr/fontVariationSettings not found

### ISSUE THREAD

**Issue by diazsasak** [BaseflowIT/flutter-permission-handler#94]
## 🐛 Bug Report

i can't build my release apk. flutter run on device/emulator work fine. but when i flutter build apk --release there is error like this. i try set compilesdkversion to 28 still doesn't work. thank you

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  *****\build\permission_handler\intermediates\res\merged\release\values\values.xml:133: error: resource android:attr/fontVariationSettings not found.
   *****\build\permission_handler\intermediates\res\merged\release\values\values.xml:134: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

### Expected behavior

my previous build and release working fine, 

### Reproduction steps

[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.3.8 at C:\src\flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\diaz\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\diaz\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.33.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 5.1.1 (API 22) (emulator)

• No issues found!

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [*] :robot: Android

**Comment by mvanbeusekom** [comment]
Please make sure you have upgraded your application to support AndroidX. Instructions can be found here: https://github.com/BaseflowIT/flutter-permission-handler/issues/81#issuecomment-465058307

**Comment by jpaardekooper** [comment]
not sure what mvanbeusekom said but i have the same issue waiting for a fix

**Comment by AteqEjaz** [comment]
Hi,

Did anyone fix this issue? Only happens when try to create a release build works fine for debug :(

**Comment by Soubatan** [comment]
Hi, anybody could fix that?
